In [5]:
import numpy as np

arr = np.array([1, 2, 3, 4, 5])

In [6]:
arr

array([1, 2, 3, 4, 5])

In [16]:
list2 = [1, 2, 3, 4, 5]
print(type(list2))
arr = np.array(list2)
print(type(arr))

<class 'list'>
<class 'numpy.ndarray'>


In [17]:

my_list = list(range(20))
my_list

[0, 1, 2, 3, 4, 5, 6, 7, 8, 9, 10, 11, 12, 13, 14, 15, 16, 17, 18, 19]

In [ ]:
arr1 = np.array([1, 2, 3, 4, 5])
arr2 = np.array([4,5,6,7,8])
mul = arr1 * arr2
mul

array([0.25      , 0.4       , 0.5       , 0.57142857, 0.625     ])

In [26]:
np.zeros(5)

array([0., 0., 0., 0., 0.])

In [27]:
np.ones(5)

array([1., 1., 1., 1., 1.])

In [ ]:
arr = np.arange(60)
print(arr.size)
print(arr.ndim)
print(arr.shape)

#convert to 2d
arr2d = arr.reshape(12,5) #rows, columns
print(arr2d)
print(arr2d[0][4]) #indexing


60
1
(60,)
[[ 0  1  2  3  4]
 [ 5  6  7  8  9]
 [10 11 12 13 14]
 [15 16 17 18 19]
 [20 21 22 23 24]
 [25 26 27 28 29]
 [30 31 32 33 34]
 [35 36 37 38 39]
 [40 41 42 43 44]
 [45 46 47 48 49]
 [50 51 52 53 54]
 [55 56 57 58 59]]
4


In [48]:
print(arr2d[0:2, 0:4]) #slicing

[[0 1 2 3]
 [5 6 7 8]]


In [49]:
arr2d[2][3] = 20
arr2d

array([[ 0,  1,  2,  3,  4],
       [ 5,  6,  7,  8,  9],
       [10, 11, 12, 20, 14],
       [15, 16, 17, 18, 19],
       [20, 21, 22, 23, 24],
       [25, 26, 27, 28, 29],
       [30, 31, 32, 33, 34],
       [35, 36, 37, 38, 39],
       [40, 41, 42, 43, 44],
       [45, 46, 47, 48, 49],
       [50, 51, 52, 53, 54],
       [55, 56, 57, 58, 59]])

In [56]:
# arr2d = arr2d.reshape(5,12) #transpose
#or

arr2d = arr2d.T
print(arr2d)
print(arr2d.shape)
print(arr2d.ndim)
print(arr2d.dtype)


[[ 0  1  2  3  4  5  6  7  8  9 10 11]
 [12 20 14 15 16 17 18 19 20 21 22 23]
 [24 25 26 27 28 29 30 31 32 33 34 35]
 [36 37 38 39 40 41 42 43 44 45 46 47]
 [48 49 50 51 52 53 54 55 56 57 58 59]]
(5, 12)
2
int64


In [59]:
arr3d = arr2d.reshape(3,4,5)
print(arr3d)

#3d to 1d
arr1d = arr3d.flatten() #or arr3d.ravel() -> different from flatten as it returns a view and flatten returns a copy
print(arr1d)


[[[ 0  1  2  3  4]
  [ 5  6  7  8  9]
  [10 11 12 20 14]
  [15 16 17 18 19]]

 [[20 21 22 23 24]
  [25 26 27 28 29]
  [30 31 32 33 34]
  [35 36 37 38 39]]

 [[40 41 42 43 44]
  [45 46 47 48 49]
  [50 51 52 53 54]
  [55 56 57 58 59]]]
[ 0  1  2  3  4  5  6  7  8  9 10 11 12 20 14 15 16 17 18 19 20 21 22 23
 24 25 26 27 28 29 30 31 32 33 34 35 36 37 38 39 40 41 42 43 44 45 46 47
 48 49 50 51 52 53 54 55 56 57 58 59]
